language: java
jdk:
  - oraclejdk8

services:
  - mongodb

before_script:
  - sleep 15
  - mongo fiazard-test conf/scripts/01_createTables.js
  - mongo fiazard-test conf/scripts/02_insertRefData.js

notifications:
  slack:
    rooms:
      - softwaresandbox:QkwyOuEOYV5NHwwPCqDx8PkB
      - fiangulartje:AccRWcnglPImsSDKzKYauQQj#general
