language: java
jdk:
  - oraclejdk8

services:
  - mongodb

before_script:
  - sleep 15
  - mongo fiazard-test --eval 'db.createCollection("products");'
  - mongo fiazard-test --eval 'db.createCollection("openinghours");'
  - mongo fiazard-test --eval 'db.createCollection("toppings");'

notifications:
  slack:
    rooms:
      - softwaresandbox:QkwyOuEOYV5NHwwPCqDx8PkB
      - fiangulartje:AccRWcnglPImsSDKzKYauQQj#general
